### ISSUE TITLE
Update API endpoint and login parameters 

### ISSUE THREAD

**Issue by irevdev** [mikiboycity/diedrichbutton#1]
var CLIENTID = "3MVG9QBLg8QGkFer3aI9gMbeTsSrXCSuw84nUJ1iPyTHGmRv5Lpgd6vhtnTcuWUGfD4OmNS7uu5iajnVozauI";
var USERNAME = "zackl@diedrichroasters.com.diedricnew";
var LOGINURL = "https://diedrichroasters--diedricnew.cs63.my.salesforce.com";

**Comment by irevdev** [comment]
For JWT to work with Salesforce Sandbox please update salesforce-jwt/lib/index.js to:

audience: 'https://login.salesforce.com' > audience: 'https://test.salesforce.com',
and uri: 'https://login.salesforce.com/services/oauth2/token', > uri: 'https://test.salesforce.com/services/oauth2/token',

**Comment by mikiboy** [comment]
I didn't have to touch library code. just could control it by sandbox param passed into.
